import {activeGoal, getProgress, updateProgress, validateState, DEPTHS} from '../core/model.js';
import {planGoal, initialState} from '../core/planner.js';
import {escapeHtml as e, renderMarkdown, safeUrl} from '../core/markdown.js';
import {chooseRepository, BrowserRepository} from '../adapters/repositories.js';
import {exportMarkdown, importMarkdown} from '../adapters/backup.js';
import {answerPractice, attemptFor, recommendLesson} from '../core/learning.js';
import {renderMedia} from './media.js';

const $ = id => document.getElementById(id);
let catalog, repository, state, view='today', lessonId=null, depth='overview', speaking=false, editStageId=null, dirtyNote=false;
let operations=Promise.resolve(), toastTimer;
const labels={overview:'30 秒概览',explanation:'慢慢看懂',deep:'再深一点'};
const heading=(tag,title,description)=>`<section class="page-heading"><div><span class="eyebrow">${tag}</span><h1>${e(title)}<span class="blue">。</span></h1><p>${e(description)}</p></div><button class="primary" data-new-goal>＋ 新的目标</button></section>`;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200);}
async function commit(change){
 const operation=operations.then(async()=>{const next=structuredClone(state);change(next);validateState(next);state=await repository.save(next,state.revision);render();return state;});
 operations=operation.catch(()=>{});return operation;
}
function goalSelector(){return `<div class="goal-switch"><label for="active-goal">正在探索</label><select id="active-goal">${state.goals.map(g=>`<option value="${g.id}" ${g.id===state.activeGoalId?'selected':''}>${e(g.title)}</option>`).join('')}</select><span>${activeGoal(state).dailyMinutes} 分钟 / 次</span></div>`;}
function contentCard(id,goal=activeGoal(state)){
 const l=catalog.lessons[id];if(!l)return `<div class="notice">内容「${e(id)}」暂未收录。可以先完成阶段任务。</div>`;
 const progress=getProgress(state,goal.id,id);
 return `<article class="lesson-card"><div class="card-top"><span class="category">${e(l.category)}</span><span>约 ${l.minutes} 分钟</span>${progress.read?'<span>· 已读</span>':''}${l.practice?'<span>· 一题自测</span>':''}${l.media.some(m=>m.type==='image')?'<span>· 图文</span>':''}</div><button class="save-button ${progress.saved?'saved':''}" data-save="${id}" data-goal-id="${goal.id}" aria-label="${progress.saved?'取消收藏':'收藏'}：${e(l.title)}" aria-pressed="${progress.saved}">${progress.saved?'▣':'▢'}</button><h3>${e(l.title)}</h3><p>${e(l.summary)}</p><div class="card-bottom"><span class="reason">${view==='saved'?e(goal.title):l.sources.length?'附有来源 · 可继续查证':'方法内容 · 按需实践'}</span><button class="text-button" data-open="${id}" data-goal-id="${goal.id}">开始了解 ↗</button></div>${view==='saved'&&progress.note?`<div class="note-preview">${e(progress.note)}</div>`:''}</article>`;
}
function tasksHtml(stage){return `<section class="task-panel"><div class="section-title"><h2>这一阶段，试着做到</h2><button class="text-button" data-edit-stage="${stage.id}">调整</button></div>${stage.tasks.map(t=>`<label class="task-row"><input type="checkbox" data-task="${t.id}" data-stage="${stage.id}" ${t.done?'checked':''}><span class="${t.done?'done':''}">${e(t.title)}</span></label>`).join('')}</section>`;}
function nextStep(goal){
 const next=recommendLesson(state,goal,catalog);
 if(!next)return `<section class="next-step"><span class="eyebrow">今天，带一点理解出去</span><h2>阅读之后，留一次真实观察</h2><p>这一阶段的阅读和已有自测已完成。试着向同行解释一个发现；答过一道题不等于已经掌握。</p></section>`;
 return `<section class="next-step"><div><span class="eyebrow">今天先做这一件</span><h2>${e(next.lesson.title)}</h2><p>${e(next.reason)} ${next.short?'这篇完整阅读超出你的时间预算，先看 30 秒概览。':`阅读约 ${next.lesson.minutes} 分钟，按自己的节奏停下。`}</p></div><button class="primary" data-open="${next.lesson.id}" data-goal-id="${goal.id}" ${next.depth?`data-start-depth="${next.depth}"`:''}>${next.short?'先看概览':'开始这一小步'} ↗</button></section>`;
}
function practiceHtml(l,p){
 const q=l.practice;if(!q)return '';
 const attempt=attemptFor(p,l),correct=attempt?.choice===q.answer;
 return `<section class="practice-panel" aria-labelledby="practice-title"><span class="eyebrow">把理解带走 · 一题自测</span><h3 id="practice-title">${e(q.prompt)}</h3><p class="form-hint">先用自己的理解选择。结果只代表这道题，不给你贴“掌握”的标签。</p><div class="practice-options">${q.options.map((option,i)=>`<button class="practice-option ${attempt?.choice===i?'selected':''}" data-answer="${i}" aria-pressed="${attempt?.choice===i}" ${attempt?'disabled':''}><span>${String.fromCharCode(65+i)}</span>${e(option)}</button>`).join('')}</div>${attempt?`<div class="practice-result ${correct?'correct':'revisit'}" role="status" tabindex="-1"><strong>${correct?'这次判断对了，再试着讲出原因。':'这里值得再想一下。'} 参考选项：${String.fromCharCode(65+q.answer)}</strong><p>${e(q.explanation)}</p><button class="text-button" data-retry-practice>重新自测</button></div>`:''}<details class="conversation-cue"><summary>带一句话去交流</summary><p><strong>可以这样说</strong><br>${e(q.say)}</p><p><strong>顺着问一句</strong><br>${e(q.ask)}</p><small>按自己的经历表达，不用照着背。</small></details></section>`;
}
function today(){
 const goal=activeGoal(state),stage=goal.stages[goal.activeStage],plugin=catalog.plugins.find(p=>p.id===goal.pluginId),read=stage.contentIds.filter(id=>getProgress(state,goal.id,id).read).length;
 const sample=goal.origin==='curated-example';
 return heading('YOUR DAILY DISCOVERY','每天理解一点',sample?'沿着青甘的示例路线，体验一条理解路径。':'让你的目标，变成今天可以迈出的一步。')+goalSelector()+`<div class="day-strip stage-strip" aria-label="选择阶段">${goal.stages.map((s,i)=>`<button class="day-button ${goal.activeStage===i?'selected':''}" data-stage-index="${i}" aria-pressed="${goal.activeStage===i}"><strong>${sample?`DAY ${i+1}`:`0${i+1}`}</strong><small>${e(s.title)}</small></button>`).join('')}</div>`+
 (sample?`<section class="hero"><img src="./assets/qinghai.jpg" alt="青海湖资料照片，非所选阶段的实时景色"><div class="hero-shade"></div><div class="hero-copy"><span class="hero-tag">旅行看懂 · 第 ${goal.activeStage+1} 天 / ${goal.stages.length} 天</span><h2>${e(stage.headline||stage.title).replace('\n','<br>')}</h2><p>${e(stage.route||stage.objective)}</p></div><span class="photo-caption">青海湖资料图 · 非当日实景</span></section>`:`<section class="goal-hero"><span class="eyebrow">${e(plugin?.name||'自定义目标')} · 阶段 ${goal.activeStage+1} / ${goal.stages.length}</span><h2>${e(stage.title)}</h2><p>${e(stage.objective)}</p><span class="small-tag">${e(goal.title)}</span></section>`)+
 nextStep(goal)+`<div class="daily-layout"><section><div class="section-title"><h2>为这一阶段准备的内容</h2><small>${stage.contentIds.length} 个主题</small></div>${!sample?'<div class="notice">以下是可直接使用的方法内容。你的主题专属知识尚待补充；当前计划由场景模板创建。</div>':''}${stage.contentIds.map(id=>contentCard(id)).join('')}${tasksHtml(stage)}<div class="end-note">完成一点，就给实践留一点时间。</div></section><aside class="daily-aside"><div class="insight"><span class="eyebrow">这一步为什么重要</span><h3>${e(stage.focus||stage.title)}</h3><p>${e(stage.objective)}</p><div class="line"></div><span class="eyebrow">我想获得的变化</span><p>${e(goal.description)}</p></div><div class="progress-box"><p>这一阶段的阅读 <strong class="blue">${read} / ${stage.contentIds.length}</strong></p><div class="progress" role="progressbar" aria-label="阶段阅读进度" aria-valuemin="0" aria-valuemax="${stage.contentIds.length||1}" aria-valuenow="${read}"><div style="width:${stage.contentIds.length?read/stage.contentIds.length*100:0}%"></div></div><small>阅读、任务完成和真正掌握，分别看待。</small><button class="text-button" data-view="goals" style="margin-top:14px">查看完整路径 ↗</button></div></aside></div>`;
}
function goals(){const goal=activeGoal(state);return heading('YOUR GROWTH PATHS','每个目标，都有自己的路','可以同时探索不同主题，也可以随时调整阶段任务。')+`<div class="goal-grid">${state.goals.map(g=>`<button class="goal-tile ${g.id===state.activeGoalId?'selected':''}" data-select-goal="${g.id}"><span class="eyebrow">${e(catalog.plugins.find(p=>p.id===g.pluginId)?.name||'自定义目标')}</span><strong>${e(g.title)}</strong><span>${g.stages.length} 个阶段 · ${g.dailyMinutes} 分钟 / 次</span></button>`).join('')}</div><div class="section-title path-heading"><h2>${e(goal.title)}的路径</h2><span class="category">${goal.origin==='curated-example'?'示例内容路线':'场景模板 · 可编辑'}</span></div><div class="timeline">${goal.stages.map((s,i)=>`<section class="stop"><span class="stop-date">阶段 ${String(i+1).padStart(2,'0')}</span><div class="stop-card"><h3>${e(s.title)}</h3><p>${e(s.objective)}</p><p>${s.tasks.filter(t=>t.done).length} / ${s.tasks.length} 项任务完成</p><div class="card-bottom"><button class="text-button" data-stage-index="${i}">进入这一阶段 ↗</button><button class="text-button" data-edit-stage="${s.id}">调整阶段</button></div></div></section>`).join('')}</div>`;}
function saved(){const cards=[];for(const goal of state.goals)for(const id of Object.keys(catalog.lessons)){const p=getProgress(state,goal.id,id);if(p.saved||p.note)cards.push(contentCard(id,goal));}return heading('YOUR FIELD NOTES','把好奇，留在这里','不同目标的见闻分别保存，同一篇内容也可以有不同的体会。')+(cards.length?cards.join(''):`<div class="empty"><h2>第一份发现，还在路上</h2><p>收藏一篇内容，或在讲解页留下自己的笔记。</p><button class="primary" data-view="today">去看今日发现</button></div>`);}
function profile(){return heading('YOUR OWN PACE','按自己的节奏探索','你决定讲解深度，也掌握自己的记录。')+`<div class="profile-grid"><section class="panel"><h2>默认讲解深度</h2><p>下次打开内容时使用，也可以随时切换。</p><div class="choice-list">${DEPTHS.map(key=>`<button class="chip ${state.preferences.depth===key?'selected':''}" data-depth-preference="${key}" aria-pressed="${state.preferences.depth===key}">${labels[key]}</button>`).join('')}</div></section><section class="panel"><h2>记录存在哪里？</h2><p>${repository.mode==='markdown'?'本地 Markdown 文件。仅当前电脑上的本地服务可以读写，不会随网站发布。':'当前浏览器。更换设备或清理浏览器数据前，可以导出备份。公开网站不上传你的个人目标和笔记。'}</p><button class="secondary" id="export-backup">导出 Markdown 备份</button><label class="import-label" for="import-backup">从备份恢复</label><input id="import-backup" type="file" accept=".md,text/markdown,text/plain"><p class="form-hint">恢复前会询问是否替换现有记录。备份包含你的个人内容。</p></section><section class="panel"><h2>我了解自己的方式</h2><p>这里仅保存你明确输入的目标、起点和阅读反馈。不会因为没点开一篇内容就判断你“不懂”。</p>${state.goals.map(g=>`<div class="memory-item">${e(g.title)}<small>${e(g.context||'尚未描述起点')}</small></div>`).join('')}</section><section class="panel"><h2>最近的阅读反馈</h2>${Object.entries(state.progress).filter(([,p])=>p.feedback).slice(-8).map(([key,p])=>{const[gid,cid]=key.split('/');return `<div class="memory-item">${e(catalog.lessons[cid]?.title||cid)}<small>${e(state.goals.find(g=>g.id===gid)?.title||'历史目标')} · ${e(p.feedback)} <button class="text-button" data-clear-feedback="${e(key)}">删除反馈</button></small></div>`;}).join('')||'<p>还没有反馈。看完内容，可以说说深浅是否适合你。</p>'}</section></div>`;}
function render(){if(!state)return;$('app').innerHTML=({today,goals,saved,profile}[view]||today)();const goal=activeGoal(state);$('active-title').textContent=goal.title;$('active-meta').textContent=`${goal.stages.length} 个阶段 · ${goal.dailyMinutes} 分钟 / 次`;$('breadcrumb-title').textContent=goal.title;$('storage-label').textContent=repository.mode==='markdown'?'记录存于本机 Markdown':'记录存于当前浏览器';$('save-count').textContent=Object.values(state.progress).filter(p=>p.saved).length;document.querySelectorAll('#navigation [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false');});}
function navigate(next){if(!['today','goals','saved','profile'].includes(next))return;view=next;history.replaceState(null,'',`#${next}`);render();window.scrollTo({top:0,behavior:'instant'});}
async function selectStage(index){const g=activeGoal(state);if(!Number.isInteger(index)||index<0||index>=g.stages.length)throw new Error('阶段不存在');await commit(s=>{activeGoal(s).activeStage=index;});navigate('today');}
function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel();speaking=false;if($('speak'))$('speak').textContent='听这段讲解';}
function renderReader(){stopSpeech();const l=catalog.lessons[lessonId],p=getProgress(state,state.activeGoalId,lessonId);$('reader-category').textContent=l.category+' · 内容库讲解';$('reader-content').innerHTML=`<h2 id="reader-title" class="reader-title">${e(l.title)}</h2><p class="reader-desc">${e(l.summary)}</p><div class="depth-tabs" role="group" aria-label="讲解深度">${DEPTHS.map(key=>`<button class="${depth===key?'active':''}" data-depth="${key}" aria-pressed="${depth===key}">${labels[key]}</button>`).join('')}</div>${renderMedia(l.media,depth)}<div class="article-body">${renderMarkdown(l.sections[depth])}</div><div class="observe"><strong>试着这样理解</strong>${renderMarkdown(l.sections.observe)}</div><details class="question"><summary>留一个问题，继续探索</summary>${renderMarkdown(l.sections.question)}</details><div class="source">${l.sources.length?'背景来源：'+l.sources.map(s=>`<a href="${e(safeUrl(s.url))}" target="_blank" rel="noopener">${e(s.title)} ↗</a><span>核查 ${e(s.checkedAt)}</span>`).join('<br>'):'内容类型：Upigo 编写的观察或学习方法。主题事实需要结合相应资料查证。'}</div>${practiceHtml(l,p)}<div class="reader-actions"><button class="primary" id="mark-read">${p.read?'已标记读完 ✓':'我读完了'}</button><button class="secondary" id="reader-save" data-save="${lessonId}" data-goal-id="${state.activeGoalId}" aria-pressed="${p.saved}">${p.saved?'已收藏 · 点击取消':'收藏这份发现'}</button><button class="secondary" id="speak">听这段讲解</button></div><div class="feedback"><p>这个深度适合你吗？</p><div class="choice-list">${['太基础','刚好','没看懂'].map(f=>`<button class="chip ${p.feedback===f?'selected':''}" data-feedback="${f}" aria-pressed="${p.feedback===f}">${f}</button>`).join('')}</div></div><label class="note-label" for="field-note">留一个发现，或一个还没懂的问题</label><textarea id="field-note" maxlength="10000" placeholder="我注意到…… / 我还想知道……">${e(p.note)}</textarea><button class="text-button" id="save-note" style="margin-top:8px">保存到我的见闻 ↗</button><p class="reader-desc">${repository.mode==='markdown'?'保存到本机 Markdown 文件':'保存到当前浏览器'} · 暂未接入自由 AI 问答</p>`;dirtyNote=false;}
async function saveDraft(){if(!dirtyNote||!$('field-note'))return;const note=$('field-note').value;await commit(s=>updateProgress(s,lessonId,{note}));dirtyNote=false;}
async function openLesson(id,goalId,startDepth){if(!catalog.lessons[id])throw new Error('内容尚未收录');if(goalId!==state.activeGoalId)await commit(s=>{s.activeGoalId=goalId;});lessonId=id;depth=DEPTHS.includes(startDepth)?startDepth:state.preferences.depth;renderReader();$('reader').showModal();$('reader').scrollTop=0;}
function showGoalForm(){const form=$('goal-form');form.reset();$('goal-error').textContent='';$('plugin-choice').innerHTML=catalog.plugins.map(p=>`<option value="${p.id}" ${p.id==='study'?'selected':''}>${e(p.name)}</option>`).join('');updateOutline();$('goal-dialog').showModal();}
function updateOutline(){const p=catalog.plugins.find(p=>p.id===$('plugin-choice').value);$('plugin-description').textContent=p.description;$('plan-outline').innerHTML='<strong>先搭建这条路径</strong>'+p.phases.map((s,i)=>`<span>${i+1}. ${e(s.title)}</span>`).join('');}
function showEdit(id){const stage=activeGoal(state).stages.find(s=>s.id===id);if(!stage)return;editStageId=id;$('stage-title').value=stage.title;$('stage-objective').value=stage.objective;$('stage-tasks').value=stage.tasks.map(t=>t.title).join('\n');$('edit-error').textContent='';$('edit-dialog').showModal();}
async function handleClick(event){
 const b=event.target.closest('button');if(!b)return;
 if(b.dataset.close){if(b.dataset.close==='reader')await saveDraft();$(b.dataset.close).close();return;}
 if(!state)return;
 if(b.dataset.view)navigate(b.dataset.view);
 else if(b.hasAttribute('data-new-goal'))showGoalForm();
 else if(b.dataset.selectGoal)await commit(s=>{s.activeGoalId=b.dataset.selectGoal;});
 else if(b.dataset.stageIndex!==undefined)await selectStage(Number(b.dataset.stageIndex));
 else if(b.dataset.open)await openLesson(b.dataset.open,b.dataset.goalId,b.dataset.startDepth);
 else if(b.dataset.answer!==undefined){await saveDraft();await commit(s=>answerPractice(s,catalog.lessons[lessonId],Number(b.dataset.answer)));renderReader();document.querySelector('.practice-result')?.focus();}
 else if(b.hasAttribute('data-retry-practice')){await saveDraft();await commit(s=>{const key=`${s.activeGoalId}/${lessonId}`;if(s.progress[key])delete s.progress[key].attempt;});renderReader();document.querySelector('[data-answer]')?.focus();}
 else if(b.dataset.save){const id=b.dataset.save,gid=b.dataset.goalId;await commit(s=>{const key=`${gid}/${id}`;s.progress[key]={...getProgress(s,gid,id),saved:!getProgress(s,gid,id).saved};});if($('reader').open){const saved=getProgress(state,gid,id).saved;$('reader-save').textContent=saved?'已收藏 · 点击取消':'收藏这份发现';$('reader-save').setAttribute('aria-pressed',String(saved));}toast('收藏已更新');}
 else if(b.dataset.depth){await saveDraft();depth=b.dataset.depth;renderReader();}
 else if(b.dataset.feedback){await saveDraft();await commit(s=>updateProgress(s,lessonId,{feedback:b.dataset.feedback}));if(b.dataset.feedback==='没看懂')depth='overview';if(b.dataset.feedback==='太基础')depth='deep';renderReader();toast('反馈已保存');}
 else if(b.dataset.depthPreference){await commit(s=>{s.preferences.depth=b.dataset.depthPreference;});toast('默认深度已更新');}
 else if(b.dataset.clearFeedback)await commit(s=>{s.progress[b.dataset.clearFeedback].feedback=null;});
 else if(b.dataset.editStage)showEdit(b.dataset.editStage);
 else if(b.id==='mark-read'){await commit(s=>updateProgress(s,lessonId,{read:true}));b.textContent='已标记读完 ✓';toast('已记录阅读，理解可以慢慢发生');}
 else if(b.id==='save-note'){await saveDraft();toast('见闻已保存');}
 else if(b.id==='speak'){
   if(!('speechSynthesis'in window))return toast('当前浏览器不支持语音朗读');if(speaking)return stopSpeech();
   const utterance=new SpeechSynthesisUtterance(document.querySelector('.article-body').innerText);utterance.lang='zh-CN';utterance.rate=.92;utterance.onend=stopSpeech;utterance.onerror=()=>{stopSpeech();toast('设备朗读暂不可用，请阅读文字版');};speaking=true;b.textContent='停止朗读';speechSynthesis.speak(utterance);
 }else if(b.id==='export-backup'){
   const url=URL.createObjectURL(new Blob([exportMarkdown(state)],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`upigo-backup-${new Date().toISOString().slice(0,10)}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
}
document.addEventListener('click',event=>handleClick(event).catch(error=>toast(error.message)));
document.addEventListener('input',event=>{if(event.target.id==='field-note')dirtyNote=true;});
document.addEventListener('change',async event=>{try{
 const input=event.target;
 if(input.id==='active-goal')await commit(s=>{s.activeGoalId=input.value;});
 if(input.id==='plugin-choice')updateOutline();
 if(input.dataset.task){const checked=input.checked;await commit(s=>{activeGoal(s).stages.find(st=>st.id===input.dataset.stage).tasks.find(t=>t.id===input.dataset.task).done=checked;});}
 if(input.id==='import-backup'&&input.files[0]){const file=input.files[0];if(file.size>2_000_000)throw new Error('备份文件过大');const incoming=importMarkdown(await file.text());if(confirm(`恢复这份备份会替换当前 ${state.goals.length} 个目标及记录。建议先导出当前备份。继续恢复？`)){await commit(s=>{const revision=s.revision;Object.assign(s,incoming,{revision});});toast('备份已恢复');}}
 }catch(error){toast(error.message);render();}});
$('goal-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const input=Object.fromEntries(new FormData(event.target));const goal=planGoal(input,catalog.plugins);await commit(s=>{s.goals.push(goal);s.activeGoalId=goal.id;});$('goal-dialog').close();navigate('goals');toast('阶段计划已创建，可以继续调整');}catch(error){$('goal-error').textContent=error.message;}finally{button.disabled=false;}});
$('edit-form').addEventListener('submit',async event=>{event.preventDefault();try{const values=Object.fromEntries(new FormData(event.target));const titles=values.tasks.split('\n').map(s=>s.trim()).filter(Boolean);if(!titles.length||titles.length>20)throw new Error('请保留 1—20 项任务');await commit(s=>{const stage=activeGoal(s).stages.find(st=>st.id===editStageId);const used=new Set();stage.tasks=titles.map(title=>{const old=stage.tasks.find(t=>t.title===title&&!used.has(t.id));if(old){used.add(old.id);return old;}return{id:`task-${crypto.randomUUID()}`,title,done:false};});stage.title=values.title.trim();stage.objective=values.objective.trim();});$('edit-dialog').close();toast('阶段已调整');}catch(error){$('edit-error').textContent=error.message;}});
$('reader').addEventListener('cancel',event=>{if(dirtyNote){event.preventDefault();saveDraft().then(()=>$('reader').close()).catch(error=>toast(error.message));}});
$('reader').addEventListener('close',stopSpeech);
$('about-button').onclick=()=>$('about').showModal();
window.addEventListener('beforeunload',event=>{if(dirtyNote){event.preventDefault();event.returnValue='';}});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(['today','goals','saved','profile'].includes(next)){view=next;render();}});
window.addEventListener('storage',event=>{if(event.key==='upigo.state.v2')toast('另一页面更新了记录，请刷新后继续');});
async function start(){try{
 const response=await fetch('./catalog.json');if(!response.ok)throw new Error('内容库读取失败');catalog=await response.json();repository=await chooseRepository();state=await repository.load(catalog);validateState(state);
 // The HTTP store is created on the first write; the same contract works on a static host.
 const next=location.hash.slice(1);if(['today','goals','saved','profile'].includes(next))view=next;render();
 }catch(error){$('app').innerHTML=`<div class="empty"><h2>暂时没能打开记录</h2><p>${e(error.message)}</p><p>为保护已有记录，没有自动清空或覆盖。请刷新重试，或检查本机存储。</p><button class="primary" id="retry-load">重新读取</button></div>`;$('retry-load').onclick=()=>location.reload();}}
await start();
